### ISSUE TITLE
How to install - no index.php?

### ISSUE THREAD

**Issue by tyeeman** [rickhurst/eatStatic#1]
Hi Rick
  I am trying to install eatstatic but I see no index.php file in the main folders. I want to install it in a subfolder of my root called "eatstatic". Please give tips to do this, thanks.

**Comment by rickhurst** [comment]
Hi Tyeeman

To achieve this will take a bit of php work - The index file you want is in the folder called siteroot. The example here is designed to be set up with that folder as the root of the site, but you could rename the folder to something else (e.g. "blog") and put it as a subfolder on your site.

You would then need to update eatStatic_config.php so it knows where to look for the library files, data files and other includes. You would probably also need to update urls within the templates to point to e.g. /blog/ rather than /

This is a very "rough and ready" example, and i'm not planning on developing it any further, so if you're not into the idea of developing it for your own scenario, you might be better off looking for a more complete blog engine instead, e.g. something like:-

http://themsaid.com/katana/

Rick
